# Site settings
title: Peephole into my brain 
description: > # this means to ignore newlines until "baseurl:"
  A lot of free time and a passion for Computer Science.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: besza

# Build settings
markdown: kramdown
highlighter: rouge

